enum ActionType {
  CURSOR_RIGHT = 'CURSOR_RIGHT',
  CURSOR_LEFT = 'CURSOR_LEFT',
  SET_CURSOR_POSITON = 'SET_CURSOR_POSITON',

  INCREMENT_REPL_COUNT = 'INCREMENT_REPL_COUNT',
  DECREMENT_REPL_COUNT = 'DECREMENT_REPL_COUNT',

  SET_COMMAND = 'SET_COMMAND',
  APPEND_COMMAND = 'APPEND_COMMAND',
  RUN_COMMAND = 'RUN_COMMAND',
}

export default ActionType
