enum ActionType {
  CURSOR_RIGHT = 'CURSOR_RIGHT',
  CURSOR_LEFT = 'CURSOR_LEFT',
  SET_CURSOR_POSITON = 'SET_CURSOR_POSITON',

  INCREMENT_REPL_COUNT = 'INCREMENT_REPL_COUNT',
  DECREMENT_REPL_COUNT = 'DECREMENT_REPL_COUNT',

  SET_COMMAND = 'SET_COMMAND',
  APPEND_COMMAND = 'APPEND_COMMAND',
  RUN_COMMAND = 'RUN_COMMAND',

  ADD_HISTORY = 'ADD_HISTORY',
  SET_HISTORIES = 'SET_HISTORIES',

  SET_HISTORY_INDEX = 'SET_HISTORY_INDEX',
  INCREMENT_HISTORY_INDEX = 'INCREMENT_HISTORY_INDEX',
  DECREMENT_HISTORY_INDEX = 'DECREMENT_HISTORY_INDEX',

  SET_COMPLETIONS = 'SET_COMPLETIONS',
  INCREMENT_COMPLETION_INDEX = 'INCREMENT_COMPLETION_INDEX',
  DECREMENT_COMPLETION_INDEX = 'DECREMENT_COMPLETION_INDEX',

  SET_CLIPBOARD = 'SET_CLIPBOARD',
}

export default ActionType
