enum ActionType {
  CURSOR_RIGHT = 'CURSOR_RIGHT',
  CURSOR_LEFT = 'CURSOR_LEFT',
  SET_CURSOR_POSITON = 'SET_CURSOR_POSITON',

  INCREMENT_REPL_COUNT = 'INCREMENT_REPL_COUNT',
  DECREMENT_REPL_COUNT = 'DECREMENT_REPL_COUNT',

  SET_COMMAND = 'SET_COMMAND',
  APPEND_COMMAND = 'APPEND_COMMAND',
  RUN_COMMAND = 'RUN_COMMAND',

  ADD_HISTORY = 'ADD_HISTORY',

  INCREMENT_HISTORY_INDEX = 'INCREMENT_HISTORY_INDEX',
  DECREMENT_HISTORY_INDEX = 'DECREMENT_HISTORY_INDEX',
}

export default ActionType
